#'GBM function for plotting output of 2-way interaction matrix as generated by the function GBMInt2
#'
#'\code{GBMInt2Plot} plots output from the function GBMInt2
#'
#'@param int2.out output from GBMInt2

#'@return plot of 2-way interaction matrix
#'@examples
#'\dontrun{
#'GBMInt2Plot(int2.out=GBMInt2.result)
#'}

#'@import gbm
#'@import reshape2
#'@export GBMInt2Plot


GBMInt2Plot <- function(int2.out){
  
  z.m <- melt(int2.out)
  
  p1 <- ggplot(z.m, aes(Var1, Var2, fill = value)) + geom_tile()+
    scale_fill_gradient(low = "blue",  high = "red") +labs(x="",y="")
  
  plot(p1)
  
}
